### ISSUE TITLE
Build error - No overload for method 'ConfigureServices' takes 2 arguments

### ISSUE THREAD

**Issue by jongalloway** [Azure/reliable-web-app-pattern-dotnet-workshop#13]
I think this was introduced in #9 - change was made to `Start/Program.cs` but not `Start/Startup.cs`

```text
Error: /home/runner/work/reliable-web-app-pattern-dotnet-workshop/reliable-web-app-pattern-dotnet-workshop/Part 7 - Performance Efficiency/start/Relecloud.Web/Program.cs(41,13): error CS1501: 
No overload for method 'ConfigureServices' takes 2 arguments 
[/home/runner/work/reliable-web-app-pattern-dotnet-workshop/reliable-web-app-pattern-dotnet-workshop/Part 7 - Performance Efficiency/start/Relecloud.Web/Relecloud.Web.csproj]
```
